
ERROR = 0

INVALID_ARGUMENT    = 1
NO_SONGS            = 2
CONFIG_WRITE_FAILED = 3
LOGIN_FAILED        = 4
FILE_ERROR          = 5
PLAYLIST_FULL       = 6
TRASH_ERROR         = 7
LIST_ERROR          = 8
CONFIG_READ_ERROR   = 9